import type { Metadata } from 'next';
import './globals.css';
import Navigation from './components/navigation/navigation';
import AuthProvider from './components/providers/SessionProvider';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <AuthProvider>
                    <Navigation />
                    {children}
                </AuthProvider>
            </body>
        </html>
    );
}
